version: '3.9'

services:

  web:
    build: .
    ports:
      - "5000:5000"
    # volumes:
    #   - .:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - postgres
    
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - postgres

      